name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Get the latest version
      id: get_version
      run: echo "DOCKER_IMAGE_VERSION=1.0.$(( $(date +'%Y%m%d%H%M%S') + 1 ))" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: alonsaban/simple-java-project:1.0.0
        context: .
        file: ./docker/Dockerfile

